# Generated by Django 4.1.7 on 2023-04-01 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_order_users_wishlist_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='users_wishlist',
        ),
        migrations.AddField(
            model_name='product',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
