# Generated by Django 4.1.7 on 2023-04-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_coupon_refund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
