# Generated by Django 4.1.7 on 2023-04-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
    ]
