# Generated by Django 4.1.7 on 2023-04-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_newsletterrecipients_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipients',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
