# Generated by Django 4.1.7 on 2023-04-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Products',
            field=models.ManyToManyField(to='app.cartitem'),
        ),
    ]
