# Generated by Django 4.1.7 on 2023-04-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(help_text='Required', max_length=255, verbose_name='delivery name')),
                ('delivery_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 999.99'}}, help_text='Maximum 999.99', max_digits=5, verbose_name='delivery price')),
                ('delivery_method', models.CharField(choices=[('IS', 'In Strore'), ('HD', 'Home Delivery'), ('DD', 'Digital Delivery')], help_text='Required', max_length=255, verbose_name='delivery method')),
                ('delivery_timeframe', models.CharField(help_text='Required', max_length=255, verbose_name='delivery timeframe')),
                ('order', models.IntegerField(default=0, help_text='Required', verbose_name='list order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
            },
        ),
    ]
