# Generated by Django 4.1.7 on 2023-04-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
